
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore;

namespace Api
{
	public class Program
	{
		public static void Main(string[] args)
		{
			CreateWebHostBuilder(args).Build().Run();
		}


		/// <summary>
		/// Creates the web host builder.
		/// </summary>
		/// <param name="args">The arguments.</param>
		/// <returns></returns>
		/// <autogeneratedoc />
		public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
			WebHost
				.CreateDefaultBuilder(args)
				.ConfigureAppConfiguration((hostingContext, config) =>
				{
					config.AddIniFile(Directory.GetCurrentDirectory() + "/../env.ini", true, reloadOnChange: false);
					config.AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", optional: true, reloadOnChange: true);
					config.AddEnvironmentVariables();
				})
				.UseStartup<Startup>();
	}
}
